# Beispiel fuer Streamlit secrets.toml
SENDER_EMAIL = "deine.email@gmail.com"
SENDER_PASSWORD = "dein_app_passwort"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
APP_URL = "https://deine-wichtel-app.streamlit.app"
USE_MONGODB = "false"
# MONGODB_URI = "mongodb+srv://user:pass@cluster.mongodb.net/"
# DATABASE_NAME = "wichtel_app"
